# This file is just for simulation of xy plotter:
xy_plotter:
    # Reads the state of all joints
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    # X-axis Controller (for both links)
    base_to_slider_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: base_to_slider_joint
        pid: {p: 1.0, i: 0.0, d: 0.0}

    # Y-axis Controller (for both links)
    slider_to_second_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: slider_to_second_joint
        pid: {p: 1.0, i: 0.0, d: 0.0}
