controller_list:
  - name: fake_eva_controller
    type: $(arg fake_execution_type)
    joints:
      - joint01
      - joint12
      - joint23
      - joint34
      - joint45
      - joint56
initial:  # Define initial robot poses per group
  - group: eva
    pose: start